name: ECS Deploy

# Trigger on push to main or manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    
    concurrency:
      group: terraform
      cancel-in-progress: true

    outputs:
      sha: ${{ steps.commit_sha.outputs.sha }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get commit SHA
        id: commit_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

  lint:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
      
      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
               
      - name: Terraform fmt check
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: TFLint
        run: tflint

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::769278709379:role/github-oidc-role
          aws-region: eu-west-2

      - name: Login to ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region eu-west-2 | \
          docker login --username AWS --password-stdin 769278709379.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t 769278709379.dkr.ecr.eu-west-2.amazonaws.com/ecs-assignment:${{ needs.setup.outputs.sha }} .

      - name: Push Docker image
        run: |
          docker push 769278709379.dkr.ecr.eu-west-2.amazonaws.com/ecs-assignment:${{ needs.setup.outputs.sha }}

  terraform-deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: [lint, build-and-push]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::769278709379:role/github-oidc-role
          aws-region: eu-west-2
# 3. Create tfvars file 👈 ADD IT HERE
      - name: Create tfvars file
        run: |
          cat <<EOF > infra/terraform.tfvars
          api_key="${{ secrets.API_KEY }}"
          db_password="${{ secrets.DB_PASSWORD }}"
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory : infra     
        run: terraform init -backend-config="bucket=ecs-assignment-tf-state-769278709379" -backend-config="region=eu-west-2"

      - name: Terraform Plan
        working-directory : infra
        run: |
          terraform plan -lock-timeout=60s -out=tfplan || \
          (echo "Retrying..." && sleep 10 && terraform plan -lock-timeout=60s -out=tfplan)

      - name: Terraform Apply
        working-directory : infra
        run: terraform apply -auto-approve tfplan
        
  post-deploy:
    name: Post-Deploy Check
    runs-on: ubuntu-latest
    needs: terraform-deploy
    steps:
      - name: Check application health
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://tm.ecs.safiaaddow.uk/health)
          if [ "$STATUS" != "200" ]; then
            echo "Application is not healthy!"
            exit 1
          else
            echo "Application is healthy!"
          fi 