name: build and Deploy App

on:
 workflow_dispatch:
    branches:
      - main
      
concurrency:
  group: terraform
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # -------------------------
      # CHECKOUT
      # -------------------------
      - name: Checkout
        uses: actions/checkout@v3

      # -------------------------
      # AWS AUTH
      # -------------------------
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::769278709379:role/github-oidc-role
          aws-region: eu-west-2

      # -------------------------
      # LOGIN TO ECR
      # -------------------------
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-west-2 | \
          docker login --username AWS --password-stdin 769278709379.dkr.ecr.eu-west-2.amazonaws.com

      # -------------------------
      # BUILD IMAGE
      # -------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t 769278709379.dkr.ecr.eu-west-2.amazonaws.com/ecs-assignment:${{ github.sha }} \
            .

      # -------------------------
      # PUSH IMAGE
      # -------------------------
      - name: Push Docker image
        run: |
          docker push \
            769278709379.dkr.ecr.eu-west-2.amazonaws.com/ecs-assignment:${{ github.sha }}

      # -------------------------
      # TERRAFORM
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=infra init

    env:
        TF_VAR_api_key: ${{ secrets.API_KEY }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Terraform Apply (Update ECS)
        run: |
          terraform -chdir=infra apply -auto-approve \
            -var="image_tag=${{ github.sha }}"

