name: Infra Provision

on:
  push:
    branches:
      - main


concurrency:
  group: terraform
  cancel-in-progress: false


jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      ##TF_VAR_api_key: ${{ secrets.API_KEY }}
      ##TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}  

      TF_VAR_api_key: "test123"   # ← HARD CODED TEST
      TF_VAR_db_password: "test456"

    steps:
      - name: Debug API key
        run: |
          echo "Value: $TF_VAR_api_key"
          if [ -z "$TF_VAR_api_key" ]; then
            echo "❌ API key is EMPTY"
            exit 1
          else
            echo "✅ API key is present"
          fi 

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::769278709379:role/github-oidc-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform -chdir=infra init \
            -backend-config="bucket=ecs-assignment-tf-state-769278709379" \
            -backend-config="region=eu-west-2"

      - name: Terraform Apply (Infra only)
        run: |
          terraform -chdir=infra apply -auto-approve \
            -var="image_tag=bootstrap"
              